// <auto-generated />
using EFFirstVSSingle.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFFirstVSSingle.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFFirstVSSingle.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseName = "DS"
                        },
                        new
                        {
                            CourseId = 2,
                            CourseName = "Algorithms"
                        },
                        new
                        {
                            CourseId = 3,
                            CourseName = "Design Patterns"
                        },
                        new
                        {
                            CourseId = 4,
                            CourseName = "OOP"
                        });
                });

            modelBuilder.Entity("EFFirstVSSingle.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Name = "Taha"
                        },
                        new
                        {
                            StudentId = 2,
                            Name = "Salah"
                        },
                        new
                        {
                            StudentId = 3,
                            Name = "Osama"
                        },
                        new
                        {
                            StudentId = 4,
                            Name = "Omar"
                        },
                        new
                        {
                            StudentId = 5,
                            Name = "Selema"
                        },
                        new
                        {
                            StudentId = 6,
                            Name = "Omar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
